# Generated by Django 4.0 on 2023-02-03 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-done']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='done',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='pending',
            new_name='review',
        ),
        migrations.AddField(
            model_name='task',
            name='unnecessary',
            field=models.BooleanField(default=False),
        ),
    ]
